apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: blog-app
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30036  # Optional: specify a custom NodePort