apiVersion: v1
kind: Secret
metadata:
  name: blog-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk # rootpassword
  MYSQL_USER: d29yZHByZXNz # wordpress
  MYSQL_PASSWORD: d29yZHByZXNzcGFzcw== # wordpresspass
  WORDPRESS_DB_USER: d29yZHByZXNz # wordpress
  WORDPRESS_DB_PASSWORD: d29yZHByZXNzcGFzcw== # wordpresspass